### PR TITLE
Add playlists manually

### PR DESCRIPTION
**Pull request by sim0mo**
Small functionality for adding a genre selector when we create a new playlist.
Also updates list of genres.

### CODE REVIEW

**Review by Flamantrose321 — COMMENTED** [review]
Nothing to report on the code.
Do you think in the future to add the possibility of having several genres for a playlist? It could be interesting

**Comment by sim0mo** [comment]
> Nothing to report on the code. Do you think in the future to add the possibility of having several genres for a playlist? It could be interesting

Yes why not. Until now, we can use the NONE member of the enum, and it will display "no specific genre"

**Review by Flamantrose321 — APPROVED** [review]
All ok

**Comment by BartLucien** [comment]
Do we also assume that the set of genre is fixed by us or that in the future, user can also set custom Genre to their playlist?

**Comment by sim0mo** [comment]
> Do we also assume that the set of genre is fixed by us or that in the future, user can also set custom Genre to their playlist?

For now it is static, since an Enum is static. We should discuss if this it is something we want to implement, but for now it is not primordial.

**Review by BartLucien — APPROVED** [review]
All good to me

**Pull request merged**
