### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by VictorSchneuwly**
Update the entire ui of the app.

### CODE REVIEW

**Comment by nathanduchesne** [comment]
i just tried pulling the branch to test out the UI on my emulator and it seems a resource is missing: 
error: resource drawable/ic_launcher_foreground (aka com.github.fribourgsdp.radio:drawable/ic_launcher_foreground) not found. -> in ic_launcher_round.xml

and idem in ic_launcher.xml
error: resource drawable/ic_launcher_foreground (aka com.github.fribourgsdp.radio:drawable/ic_launcher_foreground) not found.

Anyone else get this error? the ic_launcher_foreground.xml is in the drawable folder as well which is weird.

**Comment by shanzhaiii** [comment]
> i just tried pulling the branch to test out the UI on my emulator and it seems a resource is missing: error: resource drawable/ic_launcher_foreground (aka com.github.fribourgsdp.radio:drawable/ic_launcher_foreground) not found. -> in ic_launcher_round.xml
> 
> and idem in ic_launcher.xml error: resource drawable/ic_launcher_foreground (aka com.github.fribourgsdp.radio:drawable/ic_launcher_foreground) not found.
> 
> Anyone else get this error? the ic_launcher_foreground.xml is in the drawable folder as well which is weird.

@VictorSchneuwly I also get the same error. If you fix this, I can test on 2 devices ;)

**Comment by VictorSchneuwly** [comment]
@shanzhaiii @nathanduchesne I pushed everything I have on my part. I googled it and saw that it might be a gradle problem. As you said @nathanduchesne that you can see the XML in the folder I think this is the issues. So do a clean build and then try to build it again.

**Comment by nathanduchesne** [comment]
> @shanzhaiii @nathanduchesne I pushed everything I have on my part. I googled it and saw that it might be a gradle problem. As you said @nathanduchesne that you can see the XML in the folder I think this is the issues. So do a clean build and then try to build it again.

Yup, works now! Thanks, as I told you privately, the MainMenu looks a tiny bit squashed on a Pixel2, but hardly any android phones are as small as this one so it shouldn't be a problem. I'm testing it on a Samsung Galaxy A40 right now.

**Review by BartLucien — APPROVED** [review]
The few code looks good, it prevent bad behavior. The design is good.

**Review by nathanduchesne — COMMENTED** [review]
Just tested on Samsung Galaxy A40, it looks fine! Will the Spotify and Google buttons be decorated next week?

**Comment by VictorSchneuwly** [comment]
> Just tested on Samsung Galaxy A40, it looks fine! Will the Spotify and Google buttons be decorated next week?

The way I did it on the mock design was too hard to implement. I thought that this way looks good too so that's why I did it. But if you all agree the other one was better, I will do it next week if I have the time 👍🏻

**Comment by nathanduchesne** [comment]
> > Just tested on Samsung Galaxy A40, it looks fine! Will the Spotify and Google buttons be decorated next week?
> 
> The way I did it on the mock design was too hard to implement. I thought that this way looks good too so that's why I did it. But if you all agree the other one was better, I will do it next week if I have the time 👍🏻

Turns out I had checked it out before the commit where you designed them. They look fine no need to change them next week. All good on my side!

**Pull request merged**
